server:
 port: 7001
eureka:
  server:
#    eviction-interval-timer-in-ms: 1000   #设置清理的间隔时间，而后这个时间使用的是毫秒单位（默认是60秒）
    enable-self-preservation: false #设置为false表示关闭保护模式，默认为true，生产环境中应该打开，以避免因server和client通讯中断而导致的误清理微服务
  client:
    fetch-registry: false #是否需要从注册中心获取注册信息。因为是服务器本身，所以不需要
    register-with-eureka: false #是否需要注册到eureka。原因同上
    service-url:
#      defaultZone: http://eureka1:7001
#        defaultZone: http://admin:enjoy@localhost:7001/eureka
        defaultZone: http://admin:enjoy@eureka1:7001/eureka,http://admin:enjoy@eureka2:7002/eureka,http://admin:enjoy@eureka3:7003/eureka
  instance: # eureka实例定义
#    hostname: localhost
    hostname: eureka1 # 定义 Eureka 实例所在的主机名称

spring:
  security:
    user:
      name: admin
      password: enjoy